import { and, desc, eq, inArray } from 'drizzle-orm';
import { notificationLog, type Database } from '@assessify/db';
import {
  notificationLogEntrySchema,
  type NotificationKind,
  type NotificationLogEntry,
  type NotificationStatus,
} from '@assessify/domain';

/**
 * Data access for `notification_log` (spec 04/13). Rows map to the
 * `NotificationLogEntry` domain entity — drizzle rows never leave this layer.
 * Status *policy* (which transitions are legal, event ranking) lives in the
 * notification service; this layer only reads and writes. Infrastructure
 * failures throw — the service layer converts them to `Result` errors.
 */

export interface NotificationLogCreate {
  /** UUIDv7, generated by the service (it doubles as the queue dedupe key). */
  id: string;
  kind: NotificationKind;
  /** Recipient email address. PII — purged on GDPR erasure (spec 04). */
  recipient: string;
  template: string;
  language?: string | null;
  orderId?: string | null;
  sessionId?: string | null;
}

export interface NotificationLogRepository {
  /** Insert a new row with status `queued`. */
  insert(input: NotificationLogCreate): Promise<NotificationLogEntry>;
  findById(id: string): Promise<NotificationLogEntry | null>;
  /** Look up by the provider message id stored at send time (webhook correlation). */
  findByProviderMessageId(providerMessageId: string): Promise<NotificationLogEntry | null>;
  /** Record a successful provider hand-off: status `sent` + provider message id. */
  markSent(id: string, providerMessageId: string | null): Promise<NotificationLogEntry | null>;
  /** Set the row's status (send failure or webhook event). Returns null when the row is gone. */
  updateStatus(id: string, status: NotificationStatus): Promise<NotificationLogEntry | null>;
  /**
   * Recent entries in any of the given statuses, newest first — the admin
   * error queue's failed/bounced email view (D7 — spec 13 delivery-failure
   * visibility). Read-only; resends go through their own flow (D5).
   */
  listByStatuses(
    statuses: readonly NotificationStatus[],
    limit: number
  ): Promise<NotificationLogEntry[]>;
  /**
   * All entries of one kind referencing a session, newest first — E6's
   * dedupe read: a re-released report must not re-send `report_ready` /
   * `completion_notice` mail that already left (spec 13).
   */
  listByKindAndSession(kind: NotificationKind, sessionId: string): Promise<NotificationLogEntry[]>;
}

type NotificationLogRow = typeof notificationLog.$inferSelect;

function toEntity(row: NotificationLogRow): NotificationLogEntry {
  // Zod-validate at the boundary: rows map to domain entities, never raw.
  return notificationLogEntrySchema.parse({
    id: row.id,
    orderId: row.orderId,
    sessionId: row.sessionId,
    kind: row.kind,
    recipient: row.recipient,
    template: row.template,
    language: row.language,
    providerMessageId: row.providerMessageId,
    status: row.status,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  });
}

export function createNotificationLogRepository(db: Database): NotificationLogRepository {
  return {
    async insert(input) {
      const [row] = await db
        .insert(notificationLog)
        .values({
          id: input.id,
          kind: input.kind,
          recipient: input.recipient,
          template: input.template,
          language: input.language ?? null,
          orderId: input.orderId ?? null,
          sessionId: input.sessionId ?? null,
          status: 'queued',
        })
        .returning();
      if (!row) throw new Error('notification_log insert returned no row');
      return toEntity(row);
    },

    async findById(id) {
      const [row] = await db
        .select()
        .from(notificationLog)
        .where(eq(notificationLog.id, id))
        .limit(1);
      return row ? toEntity(row) : null;
    },

    async findByProviderMessageId(providerMessageId) {
      const [row] = await db
        .select()
        .from(notificationLog)
        .where(eq(notificationLog.providerMessageId, providerMessageId))
        .limit(1);
      return row ? toEntity(row) : null;
    },

    async markSent(id, providerMessageId) {
      const [row] = await db
        .update(notificationLog)
        .set({
          status: 'sent',
          providerMessageId,
          updatedAt: new Date(),
        })
        .where(eq(notificationLog.id, id))
        .returning();
      return row ? toEntity(row) : null;
    },

    async updateStatus(id, status) {
      const [row] = await db
        .update(notificationLog)
        .set({ status, updatedAt: new Date() })
        .where(eq(notificationLog.id, id))
        .returning();
      return row ? toEntity(row) : null;
    },

    async listByKindAndSession(kind, sessionId) {
      const rows = await db
        .select()
        .from(notificationLog)
        .where(and(eq(notificationLog.kind, kind), eq(notificationLog.sessionId, sessionId)))
        .orderBy(desc(notificationLog.createdAt), desc(notificationLog.id));
      return rows.map(toEntity);
    },

    async listByStatuses(statuses, limit) {
      if (statuses.length === 0) return [];
      const rows = await db
        .select()
        .from(notificationLog)
        .where(inArray(notificationLog.status, [...statuses]))
        .orderBy(desc(notificationLog.updatedAt), desc(notificationLog.id))
        .limit(limit);
      return rows.map(toEntity);
    },
  };
}
