import { and, desc, eq, inArray } from 'drizzle-orm';
import { payments, type Database } from '@assessify/db';
import {
  paymentSchema,
  type Payment,
  type PaymentProvider,
  type PaymentStatus,
} from '@assessify/domain';

/**
 * Data access for `payments` (spec 04/06). Rows map to the `Payment` domain
 * entity via Zod — drizzle rows never leave this layer. Status *policy*
 * (which webhook events count, idempotent replay rules) lives in the payment
 * service; this layer only reads and writes. Infrastructure failures throw —
 * the service layer converts them to `Result` errors.
 *
 * `updateStatus` is compare-and-set on the current status: concurrent
 * webhook redeliveries race on it and exactly one wins (spec 06 idempotency:
 * handlers upsert by `provider_ref` and are safe to replay).
 */

export interface PaymentCreate {
  /** UUIDv7, generated by the service. */
  id: string;
  orderId?: string | null;
  invoiceId?: string | null;
  provider: PaymentProvider;
  /** Stripe PaymentIntent id etc. — the webhook correlation key. */
  providerRef?: string | null;
  method?: 'card' | 'us_bank_account' | 'offline' | null;
  status: PaymentStatus;
  /** Integer minor units. */
  amount: number;
  currency: string;
  error?: Record<string, unknown> | null;
}

export interface PaymentStatusPatch {
  status: PaymentStatus;
  /** Structured failure/event context — ids and provider codes only, never PII. */
  error?: Record<string, unknown> | null;
}

export interface PaymentRepository {
  insert(input: PaymentCreate): Promise<Payment>;
  findById(id: string): Promise<Payment | null>;
  /** All payment attempts for an order, newest first. */
  findByOrderId(orderId: string): Promise<Payment[]>;
  /** Webhook correlation: refs are provider-scoped, so both keys are required. */
  findByProviderRef(provider: PaymentProvider, providerRef: string): Promise<Payment | null>;
  /**
   * Compare-and-set status update: applies the patch only while the row's
   * status is still one of `expectedStatuses`. Returns null when the row is
   * missing OR was concurrently updated — the service treats a lost race as
   * an already-applied (duplicate) event.
   */
  updateStatus(
    id: string,
    expectedStatuses: readonly PaymentStatus[],
    patch: PaymentStatusPatch
  ): Promise<Payment | null>;
}

type PaymentRow = typeof payments.$inferSelect;

function toEntity(row: PaymentRow): Payment {
  // Zod-validate at the boundary: rows map to domain entities, never raw.
  return paymentSchema.parse({
    id: row.id,
    orderId: row.orderId,
    invoiceId: row.invoiceId,
    provider: row.provider,
    providerRef: row.providerRef,
    method: row.method,
    status: row.status,
    amount: row.amount,
    currency: row.currency,
    error: row.error ?? null,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  });
}

export function createPaymentRepository(db: Database): PaymentRepository {
  return {
    async insert(input) {
      const [row] = await db
        .insert(payments)
        .values({
          id: input.id,
          orderId: input.orderId ?? null,
          invoiceId: input.invoiceId ?? null,
          provider: input.provider,
          providerRef: input.providerRef ?? null,
          method: input.method ?? null,
          status: input.status,
          amount: input.amount,
          currency: input.currency,
          error: input.error ?? null,
        })
        .returning();
      if (!row) throw new Error('payments insert returned no row');
      return toEntity(row);
    },

    async findById(id) {
      const [row] = await db.select().from(payments).where(eq(payments.id, id)).limit(1);
      return row ? toEntity(row) : null;
    },

    async findByOrderId(orderId) {
      const rows = await db
        .select()
        .from(payments)
        .where(eq(payments.orderId, orderId))
        .orderBy(desc(payments.createdAt));
      return rows.map(toEntity);
    },

    async findByProviderRef(provider, providerRef) {
      const [row] = await db
        .select()
        .from(payments)
        .where(and(eq(payments.provider, provider), eq(payments.providerRef, providerRef)))
        .limit(1);
      return row ? toEntity(row) : null;
    },

    async updateStatus(id, expectedStatuses, patch) {
      if (expectedStatuses.length === 0) return null;
      const set: Partial<typeof payments.$inferInsert> = {
        status: patch.status,
        updatedAt: new Date(),
      };
      if (patch.error !== undefined) set.error = patch.error;

      const rows = await db
        .update(payments)
        .set(set)
        .where(and(eq(payments.id, id), inArray(payments.status, [...expectedStatuses])))
        .returning();
      const row = rows[0];
      return row ? toEntity(row) : null;
    },
  };
}
