import { respondentSessions, scoringJobs, type Database } from '@assessify/db';
import { scoringJobSchema, type ScoringJob, type ScoringMode } from '@assessify/domain';
import { and, asc, desc, eq, inArray, lt, sql, type SQL } from 'drizzle-orm';

/**
 * Data access for `scoring_jobs` (spec 04 table, spec 08 lifecycle). Pure
 * persistence — which transitions are legal and what outcomes mean is the
 * scoring service's job. Every status write is compare-and-set on the current
 * status so worker retries, the E2 callback route and admin retries can race
 * safely: exactly one writer wins, losers see null and re-read.
 *
 * Rows map to the `ScoringJob` domain entity via Zod — drizzle rows never
 * leave this layer. Infrastructure failures throw; services convert to
 * Results. No PII lives in this table (payloads are ids/option keys/numbers).
 */

export interface ScoringJobCreate {
  /** UUIDv7, generated by the service. */
  id: string;
  sessionId: string;
  mode: ScoringMode;
  createdAt?: Date;
}

export interface ScoringJobRepository {
  /** Insert a fresh job (status `queued`, attempts 0). */
  insert(input: ScoringJobCreate): Promise<ScoringJob>;
  findById(id: string): Promise<ScoringJob | null>;
  /** All jobs for a session, newest first (re-scoring creates new rows). */
  findBySessionId(sessionId: string): Promise<ScoringJob[]>;
  /** All jobs for the sessions of an order, newest first (admin error queue). */
  findByOrderId(orderId: string): Promise<ScoringJob[]>;
  /**
   * queued|dispatched → dispatched: stamps `dispatched_at`, increments
   * `attempts` and snapshots the outbound payload. Re-entrant on purpose —
   * BullMQ backoff retries re-dispatch the same row.
   */
  markDispatched(
    id: string,
    at: Date,
    requestPayload: Record<string, unknown>
  ): Promise<ScoringJob | null>;
  /** dispatched → awaiting_callback (async engines; hash only, never the token). */
  markAwaitingCallback(id: string, callbackTokenHash: string | null): Promise<ScoringJob | null>;
  /** dispatched|awaiting_callback → completed with the validated ScoreSet. */
  complete(
    id: string,
    responsePayload: Record<string, unknown>,
    at: Date
  ): Promise<ScoringJob | null>;
  /** queued|dispatched|awaiting_callback → failed with a machine-readable error. */
  fail(id: string, error: string): Promise<ScoringJob | null>;
  /** failed → queued (admin retry): clears error, resets attempts/dispatched_at. */
  requeue(id: string): Promise<ScoringJob | null>;
  /**
   * Jobs stuck `awaiting_callback` since before `olderThan` (E2 watchdog:
   * per-product SLA sweep), oldest first.
   */
  listStuck(olderThan: Date, limit?: number): Promise<ScoringJob[]>;
}

type ScoringJobRow = typeof scoringJobs.$inferSelect;

/** Zod-validate at the boundary: rows map to domain entities, never raw. */
function toEntity(row: ScoringJobRow): ScoringJob {
  return scoringJobSchema.parse({
    id: row.id,
    sessionId: row.sessionId,
    mode: row.mode,
    status: row.status,
    callbackTokenHash: row.callbackTokenHash,
    requestPayload: row.requestPayload ?? null,
    responsePayload: row.responsePayload ?? null,
    error: row.error,
    attempts: row.attempts,
    dispatchedAt: row.dispatchedAt,
    completedAt: row.completedAt,
    createdAt: row.createdAt,
  });
}

export function createScoringJobRepository(db: Database): ScoringJobRepository {
  /** Shared CAS update: applies `set` only while status is still in `from`. */
  async function casUpdate(
    id: string,
    from: readonly string[],
    set: {
      [K in keyof typeof scoringJobs.$inferInsert]?: (typeof scoringJobs.$inferInsert)[K] | SQL;
    }
  ): Promise<ScoringJob | null> {
    const rows = await db
      .update(scoringJobs)
      .set(set)
      .where(and(eq(scoringJobs.id, id), inArray(scoringJobs.status, [...from])))
      .returning();
    const row = rows[0];
    return row ? toEntity(row) : null;
  }

  return {
    async insert(input) {
      const rows = await db
        .insert(scoringJobs)
        .values({
          id: input.id,
          sessionId: input.sessionId,
          mode: input.mode,
          status: 'queued',
          callbackTokenHash: null,
          requestPayload: null,
          responsePayload: null,
          error: null,
          attempts: 0,
          dispatchedAt: null,
          completedAt: null,
          ...(input.createdAt ? { createdAt: input.createdAt } : {}),
        })
        .returning();
      const row = rows[0];
      if (!row) throw new Error('scoring_jobs insert returned no row');
      return toEntity(row);
    },

    async findById(id) {
      const rows = await db.select().from(scoringJobs).where(eq(scoringJobs.id, id)).limit(1);
      const row = rows[0];
      return row ? toEntity(row) : null;
    },

    async findBySessionId(sessionId) {
      const rows = await db
        .select()
        .from(scoringJobs)
        .where(eq(scoringJobs.sessionId, sessionId))
        .orderBy(desc(scoringJobs.createdAt), desc(scoringJobs.id));
      return rows.map(toEntity);
    },

    async findByOrderId(orderId) {
      const rows = await db
        .select({ job: scoringJobs })
        .from(scoringJobs)
        .innerJoin(respondentSessions, eq(scoringJobs.sessionId, respondentSessions.id))
        .where(eq(respondentSessions.orderId, orderId))
        .orderBy(desc(scoringJobs.createdAt), desc(scoringJobs.id));
      return rows.map((row) => toEntity(row.job));
    },

    markDispatched(id, at, requestPayload) {
      return casUpdate(id, ['queued', 'dispatched'], {
        status: 'dispatched',
        dispatchedAt: at,
        requestPayload,
        attempts: sql`${scoringJobs.attempts} + 1`,
      });
    },

    markAwaitingCallback(id, callbackTokenHash) {
      return casUpdate(id, ['dispatched'], {
        status: 'awaiting_callback',
        callbackTokenHash,
      });
    },

    complete(id, responsePayload, at) {
      return casUpdate(id, ['dispatched', 'awaiting_callback'], {
        status: 'completed',
        responsePayload,
        completedAt: at,
        error: null,
      });
    },

    fail(id, error) {
      return casUpdate(id, ['queued', 'dispatched', 'awaiting_callback'], {
        status: 'failed',
        error,
      });
    },

    requeue(id) {
      return casUpdate(id, ['failed'], {
        status: 'queued',
        error: null,
        attempts: 0,
        dispatchedAt: null,
        callbackTokenHash: null,
      });
    },

    async listStuck(olderThan, limit = 100) {
      const rows = await db
        .select()
        .from(scoringJobs)
        .where(
          and(eq(scoringJobs.status, 'awaiting_callback'), lt(scoringJobs.dispatchedAt, olderThan))
        )
        .orderBy(asc(scoringJobs.dispatchedAt))
        .limit(limit);
      return rows.map(toEntity);
    },
  };
}
