import { z } from 'zod';

/**
 * Client entity + payload schemas (O1 — spec 04 parties; owner decisions
 * 2026-07-21: hierarchy Platform → Organization → Client → Assessment taker).
 *
 * A client belongs to exactly one organization (`organizationId`, NOT NULL —
 * `is_platform_retail` was dropped in M1). `clientNumber` is generated by the
 * repository from `client_number_seq` inside the insert (spec 04 identifier
 * conventions) — it is never client-supplied and never updatable.
 */

const currencyCodeSchema = z
  .string()
  .trim()
  .regex(/^[A-Z]{3}$/, 'Must be an ISO 4217 code, e.g. EUR');

const clientNameSchema = z.string().trim().min(1, 'Required').max(200);

/** `billing_address` / `notification_overrides` jsonb — freeform for now. */
const jsonRecordSchema = z.record(z.string(), z.unknown());

export const createClientSchema = z
  .object({
    organizationId: z.string().uuid(),
    name: clientNameSchema,
    billingEmail: z.string().trim().email().nullable().optional(),
    billingAddress: jsonRecordSchema.nullable().optional(),
    defaultCurrency: currencyCodeSchema.default('EUR'),
    timezone: z.string().trim().min(1).default('Europe/Dublin'),
    notificationOverrides: jsonRecordSchema.nullable().optional(),
  })
  .strict();

export type CreateClientInput = z.input<typeof createClientSchema>;
export type CreateClient = z.output<typeof createClientSchema>;

/**
 * Update payload — everything optional. `organizationId` is deliberately
 * absent: moving a client between organizations is not part of this CRUD
 * surface (mirrors the product-reassignment pattern — a distinct explicit
 * operation, if ever needed, with its own audit action).
 */
export const updateClientSchema = z
  .object({
    name: clientNameSchema.optional(),
    billingEmail: z.string().trim().email().nullable().optional(),
    billingAddress: jsonRecordSchema.nullable().optional(),
    defaultCurrency: currencyCodeSchema.optional(),
    timezone: z.string().trim().min(1).optional(),
    notificationOverrides: jsonRecordSchema.nullable().optional(),
  })
  .strict();

export type UpdateClientInput = z.input<typeof updateClientSchema>;
export type UpdateClient = z.output<typeof updateClientSchema>;

export interface Client {
  id: string;
  organizationId: string;
  /** From `client_number_seq`; used as the 5-digit suffix of INV references. */
  clientNumber: number;
  name: string;
  billingEmail: string | null;
  billingAddress: Record<string, unknown> | null;
  defaultCurrency: string;
  /** Set by the billing integration, not by this CRUD surface. */
  xeroContactId: string | null;
  timezone: string;
  /** `notification_overrides` jsonb — spec 13 precedence layer 2. */
  notificationOverrides: Record<string, unknown> | null;
  /** 'native' | 'legacy' (legacy imports). */
  source: string;
  legacyId: string | null;
  createdAt: Date;
  updatedAt: Date;
}
